export const SET_EMAIL = 'SET_EMAIL';
export const SET_NAME = 'SET_NAME';
export const SET_PLAN = 'SET_PLAN';
export const SET_DAY_WEIGHT_CALORIES_HISTORY = 'SET_DAY_WEIGHT_CALORIES_HISTORY';
export const SET_GOAL_REACHED = 'SET_GOAL_REACHED';
export const SET_CHATS = 'SET_CHATS';